# Generated by Django 5.0.6 on 2024-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bands',
        ),
        migrations.AddField(
            model_name='event',
            name='bands',
            field=models.CharField(default='', max_length=200),
        ),
    ]
