# Generated by Django 5.0.6 on 2024-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_remove_event_bands_event_bands'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_participants',
            field=models.IntegerField(default=0),
        ),
    ]
