# Generated by Django 5.0.6 on 2024-06-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('year_employed', models.IntegerField()),
                ('type_of_employee', models.CharField(choices=[('C', 'cleaner'), ('M', 'manager'), ('R', 'receptionist')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('has_terrace', models.BooleanField()),
                ('is_cleaned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('image', models.ImageField(upload_to='data/')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('employee_confirmed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HotelApp.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelApp.room')),
            ],
        ),
    ]
