# Generated by Django 5.0.6 on 2024-06-06 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('passengers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_created', models.IntegerField()),
                ('flies_europe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField()),
                ('flight_hours', models.IntegerField()),
                ('rank', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('airport_takeoff', models.CharField(max_length=100)),
                ('airport_landing', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='data/')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonsApp.balloon')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonsApp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonsApp.pilot')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonsApp.company')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BalloonsApp.pilot')),
            ],
        ),
    ]
